server:
    port: 3000

s3:
    accessKeyId:
    secretAccessKey:
    region:
    bucket:

dynamodb:
    accessKeyId:
    secretAccessKey:
    region:
    table:

appenders:
    - type: file
      layout:
          type: pattern
          pattern: "%d{ISO8601}   %5p [%t]    %m"
      filename: rtcstats-server_access
    - type: logLevelFilter
      level: ERROR
      appender:
          type: file
          layout:
              type: pattern
              pattern: "%d{ISO8601}   %5p [%t]    %m"
          filename: rtcstats-server_error

github:
    client_id:
    client_secret:
    callback_url:
