server:
    port: 3000

s3:


appenders:
    - type: file
      layout:
          type: pattern
          pattern: "%d{ISO8601}   %5p [%t]    %m"
      filename: snoop-server_access
    - type: logLevelFilter
      level: ERROR
      appender:
          type: file
          layout:
              type: pattern
              pattern: "%d{ISO8601}   %5p [%t]    %m"
          filename: snoop-server_error
