server:
    port: 3000

s3:
    accessKeyId: AKIAJDZALGBMGIYPVPAQ
    secretAccessKey: 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
    region: us-west-2
    bucket: snoop-data

dynamodb:
    accessKeyId: AKIAJDZALGBMGIYPVPAQ
    secretAccessKey: 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
    region: us-west-2
    table: Snoop

appenders:
    - type: file
      layout:
          type: pattern
          pattern: "%d{ISO8601}   %5p [%t]    %m"
      filename: snoop-server_access
    - type: logLevelFilter
      level: ERROR
      appender:
          type: file
          layout:
              type: pattern
              pattern: "%d{ISO8601}   %5p [%t]    %m"
          filename: snoop-server_error
